language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pytest coveralls -r requirements.txt
script:
  - coverage run --source=nifconverter --omit="*/tests/*" -m py.test

after_success:
  - coveralls
